import BookingForm from '@/Components/BookingForm';
import { notFound } from 'next/navigation';
import React from 'react';
import {
    FaEnvelope, FaBook, FaMapMarkerAlt,
    FaClock, FaUniversity, FaChalkboardTeacher,
    FaCalendarAlt, FaStar, FaCheckCircle, FaGraduationCap, FaLayerGroup
} from 'react-icons/fa';

export const metadata = {
  title: "10 Minute School || Tutor details",
  description: "Generated by create next app",
};


const TutorProfilePage = async ({ params }) => {
    const { id } = await params;

    let data;
    try {
        const res = await fetch(`${process.env.NEXT_PUBLIC_SERVER_URI}/tutors/${id}`, {
            method: "GET",
            headers: { "Content-Type": "application/json" },
            cache: "no-store",
        });

        if (res.status === 404) notFound();
        if (!res.ok) throw new Error(`Server error: ${res.status}`);
        data = await res.json();
    } catch (error) {
        throw new Error(error.message || "Failed to load tutor details.");
    }
console.log("Fetched tutor data:", data);
    return (
        <div className="min-h-screen bg-[#F8FAFC] py-8 px-4 md:px-8">
            <div className="max-w-6xl mx-auto">
                
                {/* Header Profile Section */}
                <div className="relative mb-8">
                    <div className="h-48 w-full bg-gradient-to-r from-purple-600 to-indigo-600  shadow-lg"></div>
                    
                    <div className="absolute -bottom-16 left-8 flex flex-col md:flex-row items-end gap-6 px-4 w-full">
                        <div className="relative group">
                            <img
                                src={data?.TutorBaner}
                                alt={data?.TecherName}
                                className="w-40 h-40 md:w-48 md:h-48 object-cover rounded-md border-8 border-white shadow-xl"
                            />
                            <div className="absolute -bottom-2 -right-2 bg-green-500 text-white p-2.5 rounded-2xl border-4 border-white shadow-lg">
                                <FaCheckCircle size={20} />
                            </div>
                        </div>
                        
                        <div className="mb-2 flex-1">
                            <div className="flex flex-wrap items-center gap-3">
                                <h1 className="text-3xl md:text-4xl font-black text-gray-900">{data?.TecherName}</h1>
                                <span className="bg-white/90 backdrop-blur-sm text-purple-600 px-4 py-1 rounded-xl text-xs font-black uppercase tracking-widest border border-purple-100 shadow-sm">
                                    Verified Tutor
                                </span>
                            </div>
                            <p className="text-gray-500 font-medium flex items-center gap-2 mt-2">
                                <FaEnvelope className="text-purple-400" /> {data?.TecherEmail}
                            </p>
                        </div>
                    </div>
                </div>

                {/* Spacing for Header */}
                <div className="h-10 md:h-15"></div>

                <div className="grid grid-cols-1 lg:grid-cols-12 gap-4">
                    
                    {/* LEFT CONTENT: Details */}
                    <div className="lg:col-span-7 space-y-4">
                        
                        {/* Quick Stats Grid */}
                        <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                            <StatCard icon={<FaStar className="text-amber-500" />} label="Rating" value="4.9 / 5.0" bg="bg-amber-50" />
                            <StatCard icon={<FaLayerGroup className="text-purple-500" />} label="Hourly Fee" value={`৳${data?.tutorhourlyFee}`} bg="bg-purple-50" />
                            <StatCard icon={<FaClock className="text-emerald-500" />} label="Experience" value={data?.TutorerExprence} bg="bg-emerald-50" />
                        </div>

                        {/* About/Info Card */}
                        <div className="bg-white rounded-sm p-8 shadow-sm border border-gray-100">
                            <div className="flex items-center gap-3 mb-8">
                                <div className="w-1.5 h-8 bg-purple-600 rounded-full"></div>
                                <h3 className="text-xl font-bold text-gray-900">Professional Profile</h3>
                            </div>

                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-y-8 gap-x-12">
                                <InfoItem icon={<FaBook />} label="Subject Expertise" value={data?.TutorSubject} color="text-blue-600" bg="bg-blue-50" />
                                <InfoItem icon={<FaUniversity />} label="Educational Institution" value={data?.tutorinstitution} color="text-indigo-600" bg="bg-indigo-50" />
                                <InfoItem icon={<FaMapMarkerAlt />} label="Primary Location" value={data?.TutorLocation} color="text-rose-600" bg="bg-rose-50" />
                                <InfoItem icon={<FaChalkboardTeacher />} label="Teaching Mode" value={data?.tutorteachingMode} color="text-orange-600" bg="bg-orange-50" />
                            </div>

                            <div className="mt-12 p-6 bg-slate-50 rounded-sm border border-gray-100">
                                <div className="flex items-center gap-4 mb-4">
                                    <div className="bg-white p-3 rounded-2xl shadow-sm">
                                        <FaCalendarAlt className="text-purple-600" size={20} />
                                    </div>
                                    <div>
                                        <p className="text-xs text-gray-400 font-bold uppercase tracking-widest">Schedule tutorstartDate</p>
                                        <p className="text-gray-900 font-bold">{data?.tutorstartTime} — {data?.tutorendTime}</p>
                                    </div>
                                </div>
                                <div className="flex flex-wrap gap-3">
                                    <span className="bg-white px-4 py-2 rounded-xl text-sm font-bold text-gray-600 border border-gray-100">Start Date: {data?.tutorstartDate}</span>
                                    <span className="bg-white px-4 py-2 rounded-xl text-sm font-bold text-gray-600 border border-gray-100">Available Slots: {data?.tutortotalSlots}</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* RIGHT SIDE: BOOKING FORM (Sticky) */}
                    <div className="lg:col-span-5">
                        <div className="sticky top-8">
                            <BookingForm data={data} />
                        </div>
                    </div>

                </div>
            </div>
        </div>
    );
};

// ছোট স্ট্যাট কার্ড
const StatCard = ({ icon, label, value, bg }) => (
    <div className={`${bg} p-5 rounded-3xl border border-white/50 shadow-sm transition-transform hover:scale-105 duration-300`}>
        <div className="flex items-center gap-2 mb-1">
            {icon}
            <p className="text-[10px] font-bold text-gray-500 uppercase tracking-widest">{label}</p>
        </div>
        <p className="text-lg font-black text-gray-800">{value}</p>
    </div>
);

// ইনফো আইটেম কার্ড
const InfoItem = ({ icon, label, value, color, bg }) => (
    <div className="flex items-start gap-4">
        <div className={`${bg} ${color} p-3.5 rounded-2xl shadow-sm`}>
            {React.cloneElement(icon, { size: 20 })}
        </div>
        <div>
            <p className="text-[10px] text-gray-400 font-black uppercase tracking-[0.15em] mb-1">{label}</p>
            <p className="text-gray-800 font-bold leading-tight">{value}</p>
        </div>
    </div>
);

export default TutorProfilePage;