// import { Geist, Geist_Mono } from "next/font/google";

import { ToastContainer } from "react-toastify";
import "./globals.css";
import HeroNavbar from "@/Components/HeroNavbar";
import Footer from "@/Components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <HeroNavbar />
        {children}
        <Footer/>
        <ToastContainer />
      </body>
    </html>
  );
}
