import AbailabailTutor from "@/Components/AbailabailTutor";
import Banner from "@/Components/heroBaner/Baner";
import HowItWorks from "@/Components/HowWorkSection";
import Testimonials from "@/Components/ReviewSwction";

export const metadata = {
  title: "10 Minute School || Home",
  description: "Generated by create next app",
};


export default function Home() {
  return (
    <main>
      <Banner/>
      <AbailabailTutor/>
      <HowItWorks/>
      <Testimonials/>
    </main>
  );
}
